/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingsIndexRouteImport } from './routes/landings/index'
import { Route as LandingsSlugRouteImport } from './routes/landings/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingsIndexRoute = LandingsIndexRouteImport.update({
  id: '/landings/',
  path: '/landings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingsSlugRoute = LandingsSlugRouteImport.update({
  id: '/landings/$slug',
  path: '/landings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landings/$slug': typeof LandingsSlugRoute
  '/landings/': typeof LandingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landings/$slug': typeof LandingsSlugRoute
  '/landings': typeof LandingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landings/$slug': typeof LandingsSlugRoute
  '/landings/': typeof LandingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landings/$slug' | '/landings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landings/$slug' | '/landings'
  id: '__root__' | '/' | '/landings/$slug' | '/landings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingsSlugRoute: typeof LandingsSlugRoute
  LandingsIndexRoute: typeof LandingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landings/': {
      id: '/landings/'
      path: '/landings'
      fullPath: '/landings/'
      preLoaderRoute: typeof LandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landings/$slug': {
      id: '/landings/$slug'
      path: '/landings/$slug'
      fullPath: '/landings/$slug'
      preLoaderRoute: typeof LandingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingsSlugRoute: LandingsSlugRoute,
  LandingsIndexRoute: LandingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
